// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjU0srAXo4z-HwjPFt9F0XEV1R4tapa64',
    appId: '1:760347801905:web:2e50b2531594cafa17d810',
    messagingSenderId: '760347801905',
    projectId: 'flutter-cuoiky-edf09',
    authDomain: 'flutter-cuoiky-edf09.firebaseapp.com',
    storageBucket: 'flutter-cuoiky-edf09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2S20p2duDnA41JzeShwoKixg45sOWf4g',
    appId: '1:760347801905:android:bedc89f90a7d429517d810',
    messagingSenderId: '760347801905',
    projectId: 'flutter-cuoiky-edf09',
    storageBucket: 'flutter-cuoiky-edf09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2NkifYAiEv343JO-G_DMbGCQ_RAW518',
    appId: '1:760347801905:ios:7c5dd5f4b5b1894617d810',
    messagingSenderId: '760347801905',
    projectId: 'flutter-cuoiky-edf09',
    storageBucket: 'flutter-cuoiky-edf09.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG2NkifYAiEv343JO-G_DMbGCQ_RAW518',
    appId: '1:760347801905:ios:7c5dd5f4b5b1894617d810',
    messagingSenderId: '760347801905',
    projectId: 'flutter-cuoiky-edf09',
    storageBucket: 'flutter-cuoiky-edf09.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
